### ISSUE TITLE
Accessibility issue with flu jab question - live service

### ISSUE THREAD

**Issue by edent** [nhsuk/permission-to-contact-prototype#32]
# Bug Report

## What is the issue?
On the flu jab question, it is impossible to select the "Yes" option by tapping the word "Yes".

If you tap yes, it selects no. 

## What steps are required to reproduce the issue?
Answer the questions in the service, tap the word "yes" (don't tap the radio button).

## What was the environment where this issue occurred?

* Operating System: Android 10
* Browser: Firefox

## Is there anything else you think would be useful in recreating the issue?
![Screenshot_20200721-095941](https://user-images.githubusercontent.com/837136/88037197-7df66f00-cb3c-11ea-82c0-c2374ffb3f9d.jpg)

**Comment by davidhunter08** [comment]
Thanks for reporting the bug @edent - I'll pass it on to the live service

**Comment by mcheung-nhs** [comment]
This has now been fixed on live.

**Comment by davidhunter08** [comment]
Nice one @mcheung-nhs 😎
